accountbooks/urls.py
from django.urls import path
from . import views


app_name = 'account-books'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/copy/', views.copy, name='copy'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    path('order/', views.order, name='order'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('account-books/', include('accountbooks.urls')),
]

accountbooks/models.py
from django.db import models


# Create your models here.
class AccountBook(models.Model):
    note = models.CharField(max_length=80, default='미정')
    description = models.TextField(null=True)
    category = models.CharField(max_length=20, default='미정')
    amount = models.IntegerField(default=0)
    date = models.DateField()   # 사용할 날짜
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Order(models.Model):
    '''
    True -> ASC
    False -> DESC
    '''
    id_order = models.BooleanField(default=True)
    note_order = models.BooleanField(default=True)
    category_order = models.BooleanField(default=True)
    amount_order = models.BooleanField(default=True)
    date_order = models.BooleanField(default=True)

accountbooks/views.py
from django.shortcuts import render, redirect
from datetime import datetime
from .models import AccountBook

# Create your views here.
def index(request):
    # accountbooks = AccountBook.objects.all()
    accountbooks = AccountBook.objects.all()
    if request.POST.get('ID') == "True":
        filtered = accountbooks.order_by('pk')
    else:
        filtered = accountbooks.order_by('-pk')
    
    context = {
        'accountbooks': filtered,
        'order': {
            'id': True if request.POST.get('ID') == 'True' else False,
            'note': True if request.POST.get('note') == 'True' else False,
            'category': True if request.POST.get('category') == 'True' else False,
            'amount': True if request.POST.get('amount') == 'True' else False,
            'date': True if request.POST.get('date') == 'True' else False,
        }

    }
    return render(request, 'accountbooks/index.html', context)


def detail(request, pk: int):
    accountbook = AccountBook.objects.get(pk=pk)
    context = {
        'accountbook': accountbook,
    }
    return render(request, 'accountbooks/detail.html', context)


def new(request):
    return render(request, 'accountbooks/new.html')


def create(request):
    account = AccountBook()
    g = request.POST.get
    account.note = g('note') if g('note') else '미정'
    account.category = g('category') if g('category') else '미정'
    account.date = g('date') if g('date') else datetime.today().strftime('%Y-%m-%d')
    account.description = g('description')
    account.amount = g('amount')
    # 기타 유효성 체크 코드
    # ...
    # account.date가 빈 값인지 체크
    # 빈 값이라면 -> new (X)
    # if not account.date:   # 아직 빈 값
    # if not g('date'):
    #     # 에러 페이지로 redirect
    #     return redirect('account-books:new')
    account.save()
    
    return redirect('account-books:index')


def delete (_, pk):
    g = AccountBook.objects.get(pk=pk)
    g.delete()
    
    return redirect('account-books:index')


def copy(_, pk):
    account = AccountBook.objects.get(pk=pk)
    account.pk = None
    account.note = '[복사본] ' + account.note
    account.save()
    
    return redirect('account-books:index')


def edit(request, pk):
    account = AccountBook.objects.get(pk=pk)
    context = {
        'data': account,
    }
    return render(request, 'accountbooks/edit.html', context)


def update(request, pk):
    account = AccountBook.objects.get(pk=pk)
    g = request.POST.get
    account.note = g('note') if g('note') else '미정'
    account.category = g('category') if g('category') else '미정'
    account.date = g('date') if g('date') else datetime.today().strftime('%Y-%m-%d')
    account.description = g('description')
    account.amount = g('amount')
    account.save()
    
    return redirect('account-books:detail', account.pk)


def order(request):
    g = request.POST.get
    print(g('ID'))
    context = {
        
    }
    return redirect('account-books:index')

project/views.py
from django.shortcuts import redirect


def index(_):
    # return redirect('accountbooks:index')   # urls 경로 지정 수 수정
    return redirect('account-books/')

accountbooks/templates/accountbooks/detail.html
{% extends 'base.html' %}

{% block title %}
  <title>Detail</title>
{% endblock title %}


{% block content %}
  <div class="container mt-5">
    <h1>Detail</h1>
    <h4 class="text-secondary mb-3">No. {{ accountbook.pk }}</h4>

    <div class="card card-width">
      <div class="card-header fs-5 fw-bold">
        {{ accountbook.note }}
      </div>
      <div class="card-body">
        <p>{{ accountbook.description }}</p>
        <hr>
        <div class="">
          <span>분류 : </span>
          <span class="fw-bold">{{ accountbook.category }}</span>
        </div>
        <div>
          <span>사용 금액 : </span>
          <span class="fw-bold">{{ accountbook.amount }}원</span>
        </div>
        <div>
          <span>사용 날짜 : </span>
          <span class="fw-bold">{{ accountbook.date }}</span>
        </div>
      </div>
      <div class="card-footer">
        <p class="fw-bold">{{ accountbook.updated_at }}</p>
      </div>
    </div>

    <div class="d-flex mt-3">
      <a href="{%url 'account-books:edit' accountbook.pk %}" class="btn btn-outline-primary me-2">수정하기</a>
      <form action="{% url 'account-books:delete' accountbook.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger me-2" value="삭제하기">
      </form>
      <form action="{% url 'account-books:copy' accountbook.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="복사하기">
      </form>
    </div>

    <div class="mt-5">
      <a href="{% url 'account-books:index' %}">[Home]</a>
    </div>

  </div>
{% endblock content %}

accountbooks/templates/accountbooks/edit.html
{% extends 'base.html' %}


{% block title %}
  <title>Edit & Update</title>
{% endblock title %}


{% block content %}
  <div class="container mt-5">
    <h1 class="fw-bold mb-3">Edit</h1>

    <form action="{% url 'account-books:update' data.pk %}" method="POST" class="card-width">
      {% csrf_token %}
      <div class="mb-2">
        <label for="note" class="mb-1 fw-bold form-label">내용</label>
        <input type="text" name="note" id="note" placeholder="내용" value="{{ data.note }}"
        class="form-control">
      </div>

      <div class="mb-2">
        <label for="category" class="mb-1 fw-bold form-label">분류</label>
        <input type="text" name="category" id="category" placeholder="분류" value="{{ data.category}}"
        class="form-control">
      </div>
      
      <div class="mb-2">
        <label for="amount" class="mb-1 fw-bold form-label">사용 금액</label>
        <input type="number" name="amount" id="amount" placeholder="사용 금액" value="{{ data.amount }}"
        class="form-control w-25">
      </div>
      
      <div class="mb-2">
        <label for="date" class="mb-1 fw-bold form-label">사용 날짜</label>
        <input type="date" name="date" id="date" placeholder="사용 날짜" value="{{ data.date|date:'Y-m-d'}}"
        class="form-control w-50">
      </div>
      
      <div class="mb-4">
        <label for="description" class="mb-1 fw-bold form-label">메모</label>
        <textarea type="date" name="description" id="description" placeholder="메모"
        class="form-control">{{ data.description }}</textarea>
      </div>
      
      <div class="mb-2">
        <input type="submit" class="btn btn-outline-primary" value="수정하기">
      </div>
      
      <div class="mt-5">
        <a href="{% url 'account-books:index' %}">[Home]</a>
      </div>

    </form>
  </div>
{% endblock content %}

accountbooks/templates/accountbooks/error.html
{% extends 'base.html' %}




{% block content %}

{% endblock content %}

accountbooks/templates/accountbooks/index.html
{% extends 'base.html' %}

{% block title %}
  <title>index</title>
{% endblock title %}


{% block content %}
  <div class="container mt-5">
    <h1 class="fw-bold mb-2">index</h1>

    <div class="mb-3">
      <a href="{% url 'account-books:new' %}" class="fw-bold mb-3 fs-4">New</a>
    </div>

    <div>
      <table class="table table-hover">
        <thead>  
          <tr class="">
            <th scope="col">
              <form action="{% url 'account-books:index' %}" method="POST">
                {% csrf_token %}
                <label for="ID">ID </label>
                <input type="submit" name="ID" value="{{ order.id|yesno:'False,True' }}" id="ID" hidden>
              </form>
            </th>
            <th scope="col">내용</th>
            <th scope="col">분류</th>
            <th scope="col">사용 금액</th>
            <th scope="col">사용 날짜</th>
          </tr>
        </thead>
        <tbody class="">
          {% for account in accountbooks %}
            <tr>
              <th scope="row">{{ account.pk }}</th>
              <td>
                <a class="d-block text-dark" href="{% url 'account-books:detail' account.pk %}">{{ account.note }}</a>
              </td>
              <td><a class="d-block text-dark" href="{% url 'account-books:detail' account.pk %}">{{ account.category }}</a></td>
              <td><a class="d-block text-dark" href="{% url 'account-books:detail' account.pk %}">{{ account.amount }}</a></td>
              <td><a class="d-block text-dark" href="{% url 'account-books:detail' account.pk %}">{{ account.date }}</a></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

      <div class="mt-5">
        <a href="{% url 'account-books:index' %}">[Home]</a>
      </div>

    </div>
  </div>
{% endblock content %}

accountbooks/templates/accountbooks/new.html
{% extends 'base.html' %}


{% block title %}
  <title>New & Create</title>
{% endblock title %}


{% block content %}
  <div class="container mt-5">
    <h1 class="fw-bold mb-3">New</h1>

    <form action="{% url 'account-books:create' %}" method="POST" class="card-width">
      {% csrf_token %}
      <div class="mb-2">
        <label for="note" class="mb-1 fw-bold form-label">내용</label>
        <input type="text" name="note" id="note" placeholder="내용"
        class="form-control">
      </div>
      
      <div class="mb-2">
        <label for="category" class="mb-1 fw-bold form-label">분류</label>
        <input type="text" name="category" id="category" placeholder="분류"
        class="form-control">
      </div>
      
      <div class="mb-2">
        <label for="amount" class="mb-1 fw-bold form-label">사용 금액</label>
        <input type="number" name="amount" id="amount" placeholder="사용 금액" value="0"
        class="form-control w-25">
      </div>
      
      <div class="mb-2">
        <label for="date" class="mb-1 fw-bold form-label">사용 날짜</label>
        <input type="date" name="date" id="date" placeholder="사용 날짜"
        class="form-control w-50">
      </div>
      
      <div class="mb-4">
        <label for="description" class="mb-1 fw-bold form-label">메모</label>
        <textarea type="date" name="description" id="description" placeholder="메모"
        class="form-control"></textarea>
      </div>
      
      <div class="mb-2">
        <input type="submit" class="btn btn-outline-primary" value="가계부 작성">
      </div>
      
      <div class="mt-5">
        <a href="{% url 'account-books:index' %}">[Home]</a>
      </div>

    </form>
  </div>
{% endblock content %}

templates/base.html
{% comment %} articles/base.html {% endcomment %}
<!doctype html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <link rel="icon" href="https://oopy.lazyrockets.com/api/v2/notion/image?src=https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F4c14a348-0f93-4541-91d6-dfe4f265d252%2Fhypergrowth_%25E1%2584%2585%25E1%2585%25A9%25E1%2584%2580%25E1%2585%25A9%25E1%2584%2589%25E1%2585%25B5%25E1%2586%25B7%25E1%2584%2587%25E1%2585%25A9%25E1%2586%25AF.png&blockId=a86012c3-a307-48f1-9c8f-0190bf2151cd&width=256">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block title %}{% endblock title %}
    {% block style %}{% endblock style %}
  </head>
  <body>
    {% comment %} <h1>Hello, world! <small class="text-primary">from base.html</small></h1> {% endcomment %}
    {% block content %}{% endblock content %}
    {% block script %}{% endblock script %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
  </body>
</html>